In [22]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [23]:
data = pd.read_csv('C:\\Users\\nsuguru\\Desktop\\Linear-Models-master\\task_b.csv')
data=data.iloc[:,1:]

In [24]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [25]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [40]:
std=data.std()
mean=data.mean()

In [27]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


In [ ]:
standardization(data, column wise): (column-mean(column))/std(column)

In [43]:
#data['f1']=((data['f1']-mean[0])/(std[0]))
#data['f2']=((data['f2']-mean[1])/(std[2]))
#data['f3']=((data['f3']-mean[1])/(std[2]))
data

f1           f2          f3    y
0   -0.422067 -5515.865077 -442.297315  1.0
1   -2.514085 -1834.209745 -442.678657  1.0
2   -0.002134  1063.814556 -444.042246  0.0
3    0.724391  4843.325090 -443.813726  0.0
4   -1.595658 -3165.353556 -443.548434  0.0
5    0.372624 -4775.791667 -443.006625  0.0
6   -0.262658 -9833.608214 -440.973040  1.0
7   -0.100713   785.868304 -443.162656  0.0
8   -0.084999 -5668.310943 -442.860810  0.0
9    0.092585 -3526.309060 -441.536427  1.0
10   0.707453 -6054.850017 -443.515097  0.0
11  -0.781947 -1241.757901 -443.425064  0.0
12  -0.201162  6126.902333 -441.309463  1.0
13  -0.834475 -4493.306387 -443.597124  0.0
14   0.206563  4012.027702 -444.136697  0.0
15   0.940696  1553.106812 -442.413296  0.0
16  -0.359288  -115.601140 -443.060461  0.0
17   0.269906  7801.166153 -443.133458  0.0
18  -0.650036  3652.790535 -441.229730  1.0
19  -0.607831  2967.321474 -441.876841  1.0
20   0.792796 -2385.781173 -441.051878  1.0
21   0.509294  1324.120934 -443.983255  0.0
22  -1.472191 -2129.544965 -443.955474  0.0
23  -1.473563  -823.289086 -442.772589  0.0
24  -1.033882 -2971.017480 -441.310630  1.0
25  -1.073906   747.629354 -441.518455  1.0
26  -0.101458   879.959843 -442.864016  0.0
27   0.003700  5679.767016 -441.267846  1.0
28   0.516441  -759.111688 -442.513602  1.0
29   0.460422 -1062.162831 -442.136783  1.0
..        ...          ...         ...  ...
170  0.546786  3095.437119 -441.794801  1.0
171 -0.246031  1306.876207 -441.232211  1.0
172  0.429438  3231.645449 -441.719664  1.0
173  0.780596 -4160.572908 -441.994090  1.0
174  1.137122  1033.279110 -440.905923  1.0
175  1.235200  4076.645031 -441.806311  1.0
176  1.139713   647.092620 -441.777510  1.0
177  0.061344  4682.963741 -443.764944  0.0
178  0.284676  1314.449443 -442.055480  1.0
179  0.614780   560.092895 -443.023458  0.0
180  1.071139 -2206.098999 -443.802360  0.0
181  1.590276 -2587.612432 -442.237944  0.0
182  0.883398   258.000591 -442.145009  1.0
183 -0.114853 -5151.298624 -441.880391  1.0
184 -0.639266 -4833.223525 -443.963316  0.0
185  1.276270  1348.055378 -442.008973  1.0
186 -1.172597 -1382.427186 -444.125329  0.0
187  1.054218  4680.685255 -442.447261  0.0
188 -1.247405  4366.557313 -442.083336  1.0
189 -1.307915 -1511.603897 -442.651460  1.0
190 -0.440154   -33.981014 -442.670309  0.0
191 -0.342582  3706.984402 -441.814825  1.0
192  1.703759 -1727.758805 -444.040545  0.0
193 -1.175201  6867.256166 -444.082690  0.0
194  0.807160  3431.223293 -443.319055  0.0
195  0.223769 -1464.367122 -443.869814  0.0
196 -0.098292  4018.678192 -442.335203  0.0
197  0.351185   642.290627 -443.142056  0.0
198  0.886981  -804.069434 -442.319299  0.0
199 -0.125706  2098.786021 -440.931821  1.0

[200 rows x 4 columns]

In [28]:
from sklearn import linear_model
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='hinge', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf
clf.fit(X=X, y=Y)
clf.coef_, clf.coef_.shape, clf.intercept_

-- Epoch 1
Norm: 0.61, NNZs: 3, Bias: -0.001600, T: 200, Avg. loss: 2634.084615
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.68, NNZs: 3, Bias: -0.001100, T: 400, Avg. loss: 2593.136418
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.76, NNZs: 3, Bias: -0.000900, T: 600, Avg. loss: 3308.216351
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.77, NNZs: 3, Bias: -0.002700, T: 800, Avg. loss: 3155.085896
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.93, NNZs: 3, Bias: -0.002800, T: 1000, Avg. loss: 3080.501847
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.43, NNZs: 3, Bias: -0.002700, T: 1200, Avg. loss: 3011.887174
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.69, NNZs: 3, Bias: -0.002200, T: 1400, Avg. loss: 3002.132514
Total training time: 0.00 seconds.
Convergence after 7 epochs took 0.00 seconds


(array([[ 0.38249139, -0.55764501,  0.15407861]]), (1, 3), array([-0.0022]))

In [29]:
from sklearn import linear_model
clf = linear_model.SGDClassifier(eta0=0.0001, alpha=0.0001, loss='log', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf
clf.fit(X=X, y=Y)
clf.coef_, clf.coef_.shape, clf.intercept_

-- Epoch 1
Norm: 1.08, NNZs: 3, Bias: -0.001751, T: 200, Avg. loss: 2516.147588
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.61, NNZs: 3, Bias: -0.001551, T: 400, Avg. loss: 2621.694380
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.35, NNZs: 3, Bias: -0.001850, T: 600, Avg. loss: 3285.222158
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.64, NNZs: 3, Bias: -0.003527, T: 800, Avg. loss: 3142.216822
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.48, NNZs: 3, Bias: -0.004027, T: 1000, Avg. loss: 3009.886714
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 1.40, NNZs: 3, Bias: -0.003523, T: 1200, Avg. loss: 3032.001946
Total training time: 0.00 seconds.
Convergence after 6 epochs took 0.00 seconds


(array([[ 0.37170471, -1.34463853,  0.12669033]]),
 (1, 3),
 array([-0.00352309]))

# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>